# Based on: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
# More available on: https://pre-commit.com/hooks.html

repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b1
    hooks:
    - id: black
    name: black
    language: python
    language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      additional_dependencies: [pep8-naming, flake8-docstrings, flake8-import-order]
      args: ['--config=tox.ini']
    - id: requirements-txt-fixer
    - id: check-added-large-files
    - id: detect-private-key
    - id: name-tests-test
    - id: check-ast
    - id: check-vcs-permalinks

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev:
#     hooks:
#     - id: mypy

# Formats code samples in documentation with black
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.3.0
    hooks:
    - id: blacken-docs

# # Checks for valid YAML
# -   repo: https://github.com/adrienverge/yamllint
#     rev: v1.12.1
#     hooks:
#     - id: yamllint

# # Checks makefile
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-go
#     sha: v1.0.0
#     hooks:
#     -   id: checkmake
