# pyup.io config file 
# see https://pyup.io/docs/configuration/ for all available options

label_prs: dependencies

schedule: "every week"

requirements:
  - requirements.txt:
      update: all
  - requirements-dev.txt:
      update: all