# pyup.io config file
# see https://pyup.io/docs/configuration/ for all available options

label_prs: dependancy
schedule: "every week"
pin: True
close_prs: True
search: True

assignees:
  - mikevansighem

requirements:
  - requirements.txt:
      update: all
  - requirements-dev.txt:
      update: all
  - requirements-docs.txt:
      update: all
