# Appveyor is used for Windows testing
# Travis-CI for Linux testing, OSX testing, generating coverage,
# uploading coverage to Codacy, building documentation,
# deploying documentation.

cache: pip

os: linux

language: python

# See: https://pythonhosted.org/CodeChat/.travis.yml.html
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install openssl readline
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    # I didn't do this above because it works and I'm lazy.
    brew outdated pyenv || brew upgrade pyenv
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
    # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi

install:
  - pip install tox

script:
  - tox -e $TOXENV

jobs:
  include:

    # Testing on linux
    - python: "3.6"
      env: TOXENV=py36
      os: linux
    - python: "3.7-dev"
      env: TOXENV=py37
      os: linux

    # Testing on osx, see: https://pythonhosted.org/CodeChat/.travis.yml.html
    - language: generic
      env: PYTHON=3.6
      env: TOXENV=py36
      os: osx
    - language: generic
      env: PYTHON=3.7
      env: TOXENV=py37
      os: osx

    # Formatting and docs tests
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=coverage
    - python: "3.6"
      env: TOXENV=black
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=mypy

    # Build artifacts for deployment
    - stage: build for deployment
      install:
        - pip install poetry
      script:
        - poetry install -v
        - poetry build
        on:
          tags: true

    # Publish on PyPi
    - stage: Publish on PyPi
      deploy:
        skip_cleanup: true
        provider: pypi
        user: mikevansighem
        password: $PYPI_PASSWORD
        on:
          tags: true

    # Publish on github releases
    - stage: Publish on Github releases
      deploy:
        skip_cleanup: true
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "FILE TO UPLOAD"
        on:
          tags: true

    # Documentation deployment
    - stage: deploy docs
      python: 3.6
      install:
        - pip install poetry
      script:
        - poetry install -v --extras "docs"
        - poetry run mkdocs build --verbose --clean --strict
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local_dir: site
        on:
          branch: master

  allow_failures:
    - env: TOXENV=mypy
    - os: osx

notifications:
  email:
    recipients:
      - mikevansighem@gmail.com
    on_success: change
    on_failure: always
