# Appveyor is used for Windows testing
# Travis-CI for Linux testing, OSX testing, generating coverage,
# uploading coverage to Codacy, building documentation,
# deploying documentation.

cache: pip

os:
 - linux
 - osx

language: python

install:
  - pip install tox

script:
  - tox -e $TOXENV

jobs:
  include:
    - python: "3.6"
      env: TOXENV=py36
      os: linux
    - python: "3.7-dev"
      env: TOXENV=py37
      os: linux

    - python: "3.6"
      env: TOXENV=py36
      os: osx
    - python: "3.7-dev"
      env: TOXENV=py37
      os: osx

    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=coverage
    - python: "3.6"
      env: TOXENV=black
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=mypy

    - stage: Deploy docs
      python: 3.6
      install:
        - pip install poetry
      script:
        - poetry install -v --extras "docs"
        - poetry run mkdocs build --verbose --clean --strict
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local_dir: site
        on:
          branch: master

  allow_failures:
    - env: TOXENV=mypy
    - os: osx

notifications:
  email:
    recipients:
      - mikevansighem@gmail.com
    on_success: change
    on_failure: always
