# Appveyor is used for Windows testing
# Travis-CI for Linux testing, OSX testing, generating coverage,
# uploading coverage to Codacy, building documentation,
# deploying documentation.

cache: pip

os:
 - linux
 #- osx

language: python

install:
  - pip install poetry
  - pip install tox

script:
  - tox -e $TOXENV

jobs:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=coverage
    - python: "3.6"
      env: TOXENV=black
    - python: "3.6"
      env: TOXENV=docs
    - stage: Build and deploy docs
      script: make docs-build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local_dir: site
        on:
          branch: master

notifications:
  email:
    recipients:
      - mikevansighem@gmail.com
    on_success: change
    on_failure: always
