# Appveyor is used for Windows testing.
# Travis-CI for Linux testing, OSX testing, generating coverage,
# uploading coverage to Codacy, building documentation,
# deploying documentation.

# Based on: https://github.com/PyCQA/flake8/blob/master/.appveyor.yml

build: off
deploy: off

image:
- Visual Studio 2017

install:
  - python -m pip install tox

test_script:
  - python -m tox -e py36,py37

notifications:
  - provider: Email
    to:
    - mikevansighem@gmail.com
    subject: Theia build failed
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
