site_name: 'Theia'
site_description: 'Documentation for Theia.'
site_author: 'Mike van Sighem'
site_url: 'https://mikevansighem.github.io/theia/'
copyright: 'Copyright 2018 - Mike van Sighem'
repo_name: 'mikevansighem/theia'
repo_url: 'https://github.com/mikevansighem/theia'

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - How it works: how_it_works.md
  - Testing and CI: testing_and_ci.md
  - Contributing: contributing.md
  - Environment:
    - Solar position: not_available.md
  - Hardware support:
    - MQTT-module: not_available.md

theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  logo: 'images/theia_icon.svg'
  language: 'en'

  palette:
    primary: 'purple'
    accent: 'purple'

  feature:
    tabs: true

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
